import type { MetadataRoute } from "next";
import { siteUrl } from "@/data/site";

/**
 * Generates /sitemap.xml. This is the one authoritative list of every real
 * page on the site — add a new top-level route here when one's added
 * elsewhere (`/admin` doesn't belong here; it's not a real page, and
 * robots.ts already keeps it out of search anyway).
 *
 * `lastModified` is the same build timestamp for every entry rather than a
 * hand-tracked per-page date — accurate enough for a site this size, since
 * every page is only ever regenerated by a real deploy anyway.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  const routes: { path: string; changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"]; priority: number }[] = [
    { path: "/", changeFrequency: "weekly", priority: 1 },
    { path: "/about", changeFrequency: "monthly", priority: 0.7 },
    { path: "/programs", changeFrequency: "monthly", priority: 0.7 },
    { path: "/blog", changeFrequency: "weekly", priority: 0.8 },
    { path: "/blog/gallery", changeFrequency: "monthly", priority: 0.6 },
    { path: "/parent-resources", changeFrequency: "monthly", priority: 0.6 },
    { path: "/contact", changeFrequency: "monthly", priority: 0.7 },
    { path: "/privacy-policy", changeFrequency: "yearly", priority: 0.3 },
  ];

  return routes.map((route) => ({
    url: `${siteUrl}${route.path}`,
    lastModified,
    changeFrequency: route.changeFrequency,
    priority: route.priority,
  }));
}
